cafe24 액세스 토큰 발급 API를 구현한다.
review-canvas/review-canvas-back pull request #15
Opened 2024-04-07 15:01 UTC by choihuk

### 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?

cafe24 store에서 리뷰 캔버스 앱을 설치하면 인증 프로세스를 수행하는 시나리오에서 프론트에게 제공할 cafe24 access token 발급 API를 구현했습니다.

### ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?

- cafe24 액세스 토큰 발급 API 추가
- 환경변수 추가(CAFE24_REDIRECT_URI, CAFE24_AUTHORIZATION_CODE)
- WebClient 의존성 추가

### 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?

- DirectionConverter 객체지향적으로 코드 수정

### 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요

### 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?

2024-04-07 15:08 UTC, choihuk commented on client-module/build.gradle
> +    }
실리콘 칩에서 발생하는 오류를 해결하기 위한 의존성 주입입니다.

[이슈 확인하기](https://github.com/netty/netty/issues/11020#issuecomment-1014979901)

2024-04-07 15:11 UTC, choihuk commented on client-module/src/main/java/com/romanticpipe/reviewcanvas/cafe24/Cafe24AccessToken.java
> +								LocalDateTime issuedAt) {
Cafe24AccessToken과 GetCafe24AccessTokenResponse DTO를 분리한 이유는 다음과 같습니다.

1. Jackson 라이브러리로 직렬화 시 적용할 어노테이션과 swagger에 명세하기 위한 어노테이션이 같은 클래스에 존재(SRP 위반)
2. client 모듈은 swagger 의존성이 없기에 client 모듈에 위치한 DTO는 swagger에서 제공하는 어노테이션을 사용할 수 없음(그렇다고 client에 api 명세를 위한 의존성을 추가하는 것도 이상함)

따라서 중복되지만, DTO를 분리하는 방안을 선택했습니다.

2024-04-07 15:27 UTC, choihuk commented on client-module/src/main/java/com/romanticpipe/reviewcanvas/cafe24/Cafe24Client.java
> +	private static final String AUTHORIZATION_CODE = SystemEnv.get("CAFE24_AUTHORIZATION_CODE");
properties 파일에서 받을 수도 있지만.. client 모듈에서 정의하는 대부분의 properties는 환경변수를 통해 주입받을거 같아 따로 properties 파일을 만들지 않고, 직접 주입받도록 구현했습니다.

2024-04-09 12:10 UTC, tlarbals824 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/response/GetCafe24AccessTokenResponse.java
> +	String[] scopes,
Array를 쓴이유는 무엇일까요?

2024-04-09 12:25 UTC, dldmsql requested changes
지나가다 들렸어요..~

2024-04-09 12:25 UTC, dldmsql commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/ShopUseCaseImpl.java
> +@Component
@Component 와 @Service 어노테이션 간의 차이를 알고 쓰시는 건가요.? 왜 @Component로 사용하셨는지 궁금해요.

2024-04-09 12:25 UTC, dldmsql commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/ShopUseCaseImpl.java
> +		var cafe24AccessToken = cafe24Client.getCafe24AccessToken(mallId, authCode);
왜 var로 지역변수를 정의하나요?
리턴타입을 명확히 표기하는 게, 컴파일 시점에서 타입 체크가 되니까 더 안정성이 높지 않을까 싶어서 여쭤봅니다.

2024-04-09 12:25 UTC, dldmsql commented on client-module/src/main/java/com/romanticpipe/reviewcanvas/cafe24/Cafe24AccessToken.java
> +								LocalDateTime issuedAt) {
Response 하는용이라면, LocalDateTime에 DateFormat 어노테이션으로 날짜 포멧팅을 해서 보내주면 타임존 이슈로부터 좀 자유로워지지 않을까요?

2024-04-09 12:25 UTC, dldmsql commented on client-module/src/main/java/com/romanticpipe/reviewcanvas/cafe24/Cafe24Client.java
> +	}
외부 API와 통신할 때, req/res logging을 하는 건 어떨까요? 이 정보도 나중에 오류 찾을 때 유용하답니다.

2024-04-09 12:25 UTC, dldmsql commented on common-module/src/main/java/com/romanticpipe/reviewcanvas/enumeration/Direction.java
> +		if (direction == null) {
== 도 좋지만, StringUtils.isBlank()에 대한 처리도 같이 해주면 좋을 거 같아요.

2024-04-09 13:30 UTC, choihuk commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/ShopUseCaseImpl.java
> +		var cafe24AccessToken = cafe24Client.getCafe24AccessToken(mallId, authCode);
동의합니다 👍

2024-04-09 13:30 UTC, choihuk commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/response/GetCafe24AccessTokenResponse.java
> +	String[] scopes,
리스트로 바꾸겠습니다 👍

2024-04-10 06:24 UTC, choihuk commented on common-module/src/main/java/com/romanticpipe/reviewcanvas/enumeration/Direction.java
> +		if (direction == null) {
아쉽게도 common 모듈은 spring 의존성이 없어 사용할 수 없군요..

2024-04-10 08:27 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/domain/shop/application/usecase/ShopUseCaseImpl.java
> +		var cafe24AccessToken = cafe24Client.getCafe24AccessToken(mallId, authCode);
컴파일 시점에서 타입체크가 var로 했을때 안되나요?? 되는걸로 알고있어요

이부분은 코틀린을 쓰는입장에서 의견을 드려보자면..  변수 없을때 타입없는게 익숙하네요 ㅋㅋ

2024-04-11 11:56 UTC, choihuk commented
다음 작업을 위해 해당 PR은 머지하겠습니다!

2024-04-11 11:57 UTC, merged