feat(RVCV-78): Super Admin Login API를 생성한다.
review-canvas/review-canvas-back pull request #19
Opened 2024-04-12 21:34 UTC by wodnd0131

### 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?

>  Super Admin Login API를 생성합니다/

### ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?

>  Super Admin과 Shop Admin이 각각 fk로 AdminAuthId를 가지도록 수정되었습니다.

### 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?

> 없습니다.

### 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요

> 없습니다.

### 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?

> 없습니다.

2024-04-12 21:57 UTC, wodnd0131 commented
epic 11 머지 이후 cafe24AuthenticationClient 에러로 실행이 안되서 테스트를 못해봤습니다.
이와 관련된 문제가 생기면 말씀해주세요.

2024-04-13 01:44 UTC, hungrytech requested changes
전체적으로 증복코드가 많고, 가독성이 않좋습니다.

리펙토링 기법을 공부해보시면 좋을것 같아요

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/AuthFilter.java
> +		filterChain.doFilter(request, response);
catch 가 이렇게 되어있으니 정말 코드보기가 어려운것 같아요 🥲

메서드 분리, 예외 type별 확인 로직을 따로 두어서 해소하면 어떨까요?

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/CustomAccessDeniedHandler.java
> +	}
component로 bean을 두었는데 ObjectMapper를 따로 생성하시는 이유가 있을까요?

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/CustomEntryPoint.java
> +	}
ObjectMapper 위와 동일

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/SecurtyErrorCode.java
> +	}
오버라이딩했는데 따로 Lombok Getter를 주신 이유가 있을까요?

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	private long refreshTokenValidityTime;
second를 long으로 받고있는데 duration으로 받으면 어떨까요?
yaml, 코드 표현이 좀더 좋아질것 같네요

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	}
토큰생성할때  (new Date()).getTime 로직들이 다들어가는데 증복 로직인것 같네요

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +		return admin;
변수를 두고 처리하는게 아니라 한번에 처리 할 수 있을것 같은데요? (early return)

```suggestion
		AdminInterface admin;
		if (authorities.stream()
			.anyMatch(authority -> authority.getAuthority().equals(Role.SUPER_ADMIN_ROLE.toString()))) {
			return this.superAdminValidator.validByAuthId(Long.parseLong(claims.get(AUTH_ID).toString()));
		}
		
		return this.shopAdminValidator.validByAuthId(Long.parseLong(claims.get(AUTH_ID).toString()));
```


그리고 if문에서 이렇게 작성해버리면 가독성이 많이 않좋네요 아래처럼 변경하면 좋을것 같네요 


최종 코드 

```suggestion
public AdminInterface getAdmin(Claims claims) {
		Collection<? extends GrantedAuthority> authorities = getAuthorites(claims);

		if (isSuperAdmin(authorities)) {
			return this.superAdminValidator.validByAuthId(Long.parseLong(claims.get(AUTH_ID).toString()));
		}
		
		return this.shopAdminValidator.validByAuthId(Long.parseLong(claims.get(AUTH_ID).toString()));
	}

	private List<SimpleGrantedAuthority> getAuthorites(Claims claims) {
		return Arrays.stream(claims.get(AUTHORITIES_KEY).toString().split(","))
			.map(SimpleGrantedAuthority::new)
			.collect(Collectors.toList());
	}

	private boolean isSuperAdmin(Collection<? extends GrantedAuthority> authorities) {
		return authorities.stream().anyMatch(authority -> authority.getAuthority().equals(Role.SUPER_ADMIN_ROLE.toString()));
	}
```

2024-04-13 01:44 UTC, hungrytech commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	}
아래처럼 바꾸면 코드가독성이 높아질것 같네요 그리고 new Date를 그대로 넣는건 제어할 수 있는 코드일까요? 

테스트코드를 작성한다 생각해보세요 

```suggestion 
public boolean isExpiredToken(String refreshToken, Date currentDate) {
		if (refreshToken.isEmpty() || refreshToken.equals(DELETED_TOKEN)) {
			return true;
		}
		Claims claims = parseClaims(refreshToken);
		
		return claims.getExpiration().before(currentDate);
	}
```

2024-04-13 09:08 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/AuthFilter.java
> +		filterChain.doFilter(request, response);
accesstoken만 만료된 경우, 프론트 측의 재요청 없이 토큰을 재발급하는 것을 만들어 본 것입니다.
수정하더라도 좋은 구조로 만들기 어려워보여서 재요청 api를 추가하는 쪽으로 수정했습니다.

2024-04-13 09:09 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/CustomAccessDeniedHandler.java
> +	}
ObjectMapper에 대한 이해가 부족했던 것 같습니다. 의존성 주입 받을 수 있도록 수정했습니다.

2024-04-13 09:11 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/SecurtyErrorCode.java
> +	}
죄송합니다. 제대로 확인하지 않았습니다.

2024-04-13 09:12 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	private long refreshTokenValidityTime;
duration 기반이 훨씬 보기 편한 것 같습니다. 이에 맞추어 수정했습니다.
더 좋은 방향성에 대해 고려해보지 않았던 것 같습니다.

2024-04-13 09:16 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	}
개발 당시 중복양이 적어 메소드로 뺴도 코드 총량이 비슷할 것이라 판단했는데,
가독성 적인 면에서도 메소드를 빼는 것이 좋고,
코드 총량도 결국 줄어드니 생각이 짧았던 것 같습니다.
리뷰에 맞게 반영하였습니다.

2024-04-13 09:39 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +		return admin;
코드가 작동하니 그냥 만족하고 고치는 것은 생각하지 않았던 것 같습니다.
가독성 고려와 불필요한 부분 없도록 주의하도록 하겠습니다.
좋은 조언 감사합니다.

2024-04-13 09:41 UTC, wodnd0131 commented on api-module/src/main/java/com/romanticpipe/reviewcanvas/common/security/TokenProvider.java
> +	}
테스트 코드 작성시 필요한, 제어되야 할 부분이라는 게 처음 보이네요,,
전혀 고려하지 못했던 것 같습니다.
리뷰에 맞게 반영하도록 하겠습니다.

2024-04-15 05:26 UTC, choihuk approved these changes
수고하셨습니다~

2024-04-15 05:27 UTC, merged